version: '3.1'
volumes:
  mysql-volume:

services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
     - mysql-volume:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: rootpass
     MYSQL_DATABASE: db
     MYSQL_USER: user
     MYSQL_PASSWORD: supersecret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
    ports:
      - 80:80
    depends_on:
      - mysql