version: '3'
services:
  db:
    image: mariadb:10.3
    restart: on-failure
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=bom
      - MYSQL_USER=root
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
#      - /data/mysql:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - 2376:2376
