version: '3'
services:
  db:
    image: mariadb:10.3
    restart: on-failure
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=bom_demo_test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_USER=user
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
#      - /data/mysql:/var/lib/mysql
  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   links:
    - db
   ports:
    - 8080:80
   environment:
    PMA_HOST: db
   depends_on:
    - db
  redis:
    image: redis:alpine
    ports:
      - 2376:2376
    depends_on:
     - db